"""AI Investigation API routes.

Allows users to ask questions about the analyzed repository.
Answers use the knowledge graph and evidence system.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from asa.core.evidence import Evidence, Finding

router = APIRouter()


class InvestigationRequest(BaseModel):
    """A question about the repository."""

    question: str = Field(..., min_length=3, max_length=500)
    analysis_id: str | None = None


class InvestigationResponse(BaseModel):
    """Response to an investigation question."""

    question: str
    answer: str
    confidence: float
    evidence: list[dict]
    sources: list[str]
    reasoning: str
    disclaimer: str = "This answer was generated by AI analysis. Verify critical conclusions with source code."


@router.post("/ask")
async def ask_question(request: InvestigationRequest) -> InvestigationResponse:
    """Ask a question about an analyzed repository."""
    # Without an LLM, we provide a template-based response
    # With an LLM enabled, this would query the knowledge graph and generate a response

    question_lower = request.question.lower()

    # Generate a structured answer based on common question patterns
    if any(w in question_lower for w in ["depend", "requirement", "library", "package"]):
        answer = (
            "Based on static analysis of the repository, I found the following "
            "dependency information. Check the dependency graph for the complete "
            "picture of internal and external dependencies."
        )
    elif any(w in question_lower for w in ["api", "endpoint", "route", "interface"]):
        answer = (
            "The repository's API surface can be determined by analyzing exported "
            "functions, HTTP route definitions, and public interfaces. "
            "Review the code explorer for detected endpoints."
        )
    elif any(w in question_lower for w in ["security", "vulnerability", "secret", "credential"]):
        answer = (
            "Security analysis examines patterns like hardcoded credentials, "
            "insecure configurations, and dependency vulnerabilities. "
            "Check the security findings for specific concerns."
        )
    elif any(w in question_lower for w in ["test", "coverage", "testing"]):
        answer = (
            "The test infrastructure analysis identifies test files, frameworks, "
            "and coverage patterns. Check the dependency graph for TESTED_BY relationships."
        )
    elif any(w in question_lower for w in ["architecture", "design", "structure"]):
        answer = (
            "Architecture analysis examines module boundaries, dependency directions, "
            "coupling metrics, and component relationships. "
            "The architecture graph visualization provides an interactive view."
        )
    else:
        answer = (
            "I can help analyze the repository structure, dependencies, architecture, "
            "security, and testing. Please ask a more specific question about what "
            "aspect of the codebase you'd like to understand."
        )

    # Always include evidence disclaimer
    return InvestigationResponse(
        question=request.question,
        answer=answer,
        confidence=0.6,
        evidence=[],
        sources=[],
        reasoning="Template-based response. Enable LLM provider for AI-powered investigation.",
    )


@router.get("/history")
async def investigation_history(limit: int = Query(20, ge=1, le=100)) -> list[dict]:
    """Get history of investigation questions."""
    # Placeholder — would be stored in database
    return []
